### ISSUE TITLE
KSS BuildSystem support

### ISSUE THREAD

**Issue by stevenklassen8376** [klassen-software-solutions/LicenseScanner#19]
This will cover the following items:

- [x] #5 Locating and identifying license for a given directory
- [x] #8 Deep dependancy searching
- [x] #15 support for the KSS BuildSystem format
- [x] #14 support for pip in the KSS BuildSystem format
