### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by stevenklassen8376** [klassen-software-solutions/LicenseScanner#21]
This will cover the following items:

- [x] #2 Bash script entry point
- [x] #4 JSON format
- [x] #6 GitHub recognition as a "fallback"
- [x] #7 Support for manually created entries
- [x] #9 Normalization based on SPDX
- [x] #10 Labelling of unrecognized licenses
- [x] #24 Runnable on macOS
